// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcjDWgpZwt0mR_eHXcJY7p5K4uHq0AMqM',
    appId: '1:783546365438:web:eda8c87580b042d0b73caf',
    messagingSenderId: '783546365438',
    projectId: 'grouptwo-chattingapp',
    authDomain: 'grouptwo-chattingapp.firebaseapp.com',
    storageBucket: 'grouptwo-chattingapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSw_PiXfTJDsZuBkEurbOVClamhxsNT_g',
    appId: '1:783546365438:android:47d96a358288c566b73caf',
    messagingSenderId: '783546365438',
    projectId: 'grouptwo-chattingapp',
    storageBucket: 'grouptwo-chattingapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcjDWgpZwt0mR_eHXcJY7p5K4uHq0AMqM',
    appId: '1:783546365438:web:9eaed7eef700084ab73caf',
    messagingSenderId: '783546365438',
    projectId: 'grouptwo-chattingapp',
    authDomain: 'grouptwo-chattingapp.firebaseapp.com',
    storageBucket: 'grouptwo-chattingapp.firebasestorage.app',
  );
}
